 spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp15d57kte662k87u6o.mysql.rds.aliyuncs.com:3306/toptensinger?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#    username: root
#    password: JKscjdsg1!
    url: jdbc:mysql://localhost:3306/toptensinger?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: uAiqwVwjJ8-i
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true